// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SmileDetector",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "SmileDetector",
            targets: ["AppModule"],
            bundleIdentifier: "com.randy.smiledetector",
            teamIdentifier: "8PHTJZGGL9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeLeft,
                .landscapeRight,
                .portraitUpsideDown
            ],
            capabilities: [
                .camera(purposeString: "Smile Detection")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("ML"),
                .process("Assets.xcassets"),
                .copy("Neptune.usdz")
            ]
        )
    ]
)